apiVersion: v1
kind: Service

metadata:
  name: web-service

spec:
  selector:
<<<<<<< HEAD
    app: web-service
=======
    app: web-ahsgdf
>>>>>>> 407f4652962adcb89e293b339fc7ad0374b3effc

  ports:
    - port: 80
      targetPort: 80

  type: ClusterIP